### ISSUE TITLE
Allow project to customise the table format

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/gh-actions-html-table-generator#2]
- pass in the cell html with variables

**Comment by alrifay** [comment]
You are creating a new cell for each field in line *11*
https://github.com/eddiejaoude/github-actions-reader-writer/blob/722d7becf2b6a67b14b71e7a825913e45afc3766/index.js#L10-L11

i think it should be something similar to this: 
```javascript
let htmlCell = core.getInput('html-cell');
objectFieldNames.forEach((name) => {
    htmlCell = htmlCell.replace(new RegExp(`{{ ${name} }}`), cell[name]);
});
```

**Comment by eddiejaoude** [comment]
Oh good spot 🤦‍♂️

**Comment by eddiejaoude** [comment]
😂 😂 😂 😂 

<img width="1132" alt="Screenshot 2020-08-24 at 20 11 13" src="https://user-images.githubusercontent.com/624760/91085872-fb366780-e645-11ea-9063-5ffec13f7e21.png">

**Comment by alrifay** [comment]
You can't use `join` on a string 😁
https://github.com/eddiejaoude/github-actions-reader-writer/blob/0f182296db9f8f584ebd04ed5690475d35d9ed25/index.js#L17

**Comment by eddiejaoude** [comment]
@alrifay you really have Eagle Eyes, thank you 👍
