### ISSUE TITLE
[Bug] Unknown Error and Error is not Displaying

### ISSUE THREAD

**Issue by AakarshTeja** [eddiejaoude/gh-actions-html-table-generator#20]
I've been trying to add this HTML table action. But it fails to write in the readme file. And the error is not displaying.

link:     https://github.com/AakarshTeja/AakarshTeja/runs/1268344225

![image](https://user-images.githubusercontent.com/42816874/96336514-00d88880-109e-11eb-8d82-1cd8a1d67b19.png)

**Comment by AakarshTeja** [comment]
[![image](https://user-images.githubusercontent.com/42816874/96346357-0099b680-10b9-11eb-99b3-fb5d6c2dcfc2.png)](https://github.com/AakarshTeja/AakarshTeja/runs/1268726827?check_suite_focus=true)


- After some console.logs() I've got the output as in the above image which states that the start and end sections are not found.
- But the Readme.md file contains the data-section start and end.


[![image](https://user-images.githubusercontent.com/42816874/96346394-3d65ad80-10b9-11eb-89ac-55f3c4ea47e4.png)](https://raw.githubusercontent.com/AakarshTeja/AakarshTeja/master/README.md)


@eddiejaoude  Can you check this one?

**Comment by AllanRegush** [comment]
The `Error: {}` comes from the readme box library.

Could you link to your project? It because it can't find the HTML Comment section header.

**Comment by alrifay** [comment]
[readme-box](https://github.com/JasonEtco/readme-box) expects a newline after the start tag
![image](https://user-images.githubusercontent.com/19517534/96355331-bdebd480-10e0-11eb-80ee-6eb7fb1c75bc.png)
and you have an extra whitespace, try removing it and the action should work.
![image](https://user-images.githubusercontent.com/19517534/96355389-85002f80-10e1-11eb-823b-1744f34dcf71.png)

**Comment by eddiejaoude** [comment]
Awesome spot @alrifay 🦅 👀

**Comment by AakarshTeja** [comment]
@alrifay  Super dude🤩, Thank you so much
OMG!!!! one extra space made me a mad person for one day😅
Never going to make this mistake again.

**Comment by eddiejaoude** [comment]
@AakarshTeja in VSCode (and other IDEs), you can have it trim any white space on save to avoid this issue

**Comment by AakarshTeja** [comment]
> @AakarshTeja in VSCode (and other IDEs), you can have it trim any white space on save to avoid this issue

Yeah, since it's a minor change and that too for working with GitHub Actions, I've worked on the browser itself😁. 
But once we get the codespaces in GitHub, working on projects will be very easy and rapid😎😋. Hope we will get that soon.

**Comment by eddiejaoude** [comment]
Ah ok, I see 👍 . Yes CodeSpaces is going to be awesome 💪
