### ISSUE TITLE
Make the file to push to be customizable

### ISSUE THREAD

**Issue by Panquesito7** [eddiejaoude/gh-actions-html-table-generator#24]
I am working on a simple GitHub Pages for the [Awesome GitHub profiles](https://github.com/EddieHubCommunity/awesome-github-profiles) repository, but I would like to push to another file named `profiles.md`. It'd be great if the file to push to be customizable.

On my fork of this repository, I tried doing it, but I couldn't do it.
**EDIT:** I'm still trying to do it, though.

Can anybody help me with this? Thank you! 😄

**Comment by eddiejaoude** [comment]
Thank you for doing this 👍

**Comment by suitupstan** [comment]
@Panquesito7 if you are facing any issues, please let us know, we would love to help!

**Comment by Panquesito7** [comment]
Closing as this is already implemented. :)
