### ISSUE TITLE
[FEATURE] Customize section on the readme file

### ISSUE THREAD

**Issue by guibranco** [eddiejaoude/gh-actions-html-table-generator#38]
### Description

Currently this actions looks for 

`<!--START_SECTION:data-section-->`
and 
`<!--END_SECTION:data-section-->`

The idea is to allow us to set the `data-section` name instead of a fixed one, so we can have multiple data sections in a single file that will be updated by different actions...

**Comment by guibranco** [comment]
Not stale, awaiting for approval

**Comment by eddiejaoude** [comment]
Sorry I missed the notification

**Comment by guibranco** [comment]
@eddiejaoude the PR is still open...

**Comment by eddiejaoude** [comment]
I have reopened it

**Comment by guibranco** [comment]
The changes requested in the PR have already been made...What is pending?

**Comment by eddiejaoude** [comment]
Sorry just review, looks great, I just left 1 small comment

**Comment by guibranco** [comment]
@eddiejaoude I create another PR in place of the first one. Please take a look when you have time 

PR: #40

**Comment by eddiejaoude** [comment]
ok sure 👍
