### ISSUE TITLE
[FEATURE] Upgrade Node.js from version 16 to version 20

### ISSUE THREAD

**Issue by guibranco** [eddiejaoude/gh-actions-html-table-generator#41]
### Description

Upgrade the Node.js version used by this GitHub action since the current one will be forcibly upgraded by GHA runtime.

Official docs: [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

### Additional information

GitHub Actions will automatically run using the supported version (Node.js version 20) when they remove version 16 but keeping an unsupported version in the actions generates warning messages when we run it.

**Comment by guibranco** [comment]
@eddiejaoude, could you take a look at this one when you have a chance?

**Comment by guibranco** [comment]
Waiting approval in the PR

**Comment by eddiejaoude** [comment]
Sorry, looking at it now
