### ISSUE TITLE
YAML token indentation error in action.yml

### ISSUE THREAD

**Issue by guibranco** [eddiejaoude/gh-actions-html-table-generator#43]
### Description

There is an error in the `action.yml` file on line 28. The parameter is with an extra space.

### Screenshots

![image](https://github.com/EddieHubCommunity/gh-actions-html-table-generator/assets/3362854/010525ab-b9c8-4a0f-a179-6adc012197da)

### Additional information

This bug was introduced by myself in #

**Comment by guibranco** [comment]
Waiting for approval in PR #44

**Comment by guibranco** [comment]
@eddiejaoude this was waiting for review...

**Comment by eddiejaoude** [comment]
Sorry for the delay. Reviewed and merged
