### ISSUE TITLE
Generate a new release with the updated codebase

### ISSUE THREAD

**Issue by guibranco** [eddiejaoude/gh-actions-html-table-generator#45]
### Description

The currently available version is `v0.1.1`; it's dated 2020, but we have made a lot of changes since this date...

Could you please generate an updated release with the current codebase version?

### Screenshots

![image](https://github.com/EddieHubCommunity/gh-actions-html-table-generator/assets/3362854/06e4743c-959f-44e2-8d58-332abde196c0)

![image](https://github.com/EddieHubCommunity/gh-actions-html-table-generator/assets/3362854/cac25a3b-5b3d-4e27-beb3-368fe77a37b8)

### Additional information

It would be nice to have a GitHub Action that generates the release every time we push to the main.

Let me know if you are keen on this. I can create a PR to add this GH Action.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

Yes having a GH Action to create a release would be great. We have this happening on our other EddieHub projects using the commit message to create the SEMVER - please can you use one of those existing GH Actions

**Comment by guibranco** [comment]
@eddiejaoude yes, sure!

**Comment by guibranco** [comment]
@eddiejaoude PR #46 was raised. Please review it when you have a chance!

**Comment by eddiejaoude** [comment]
Sorry for the delay! Merged 👍
